package config

type Token struct {
	Symbol   string
	Name     string
	Decimals int
	Address  string
	IsERC20  bool
	IsLP     bool
}

type CToken struct {
	Symbol     string
	Name       string
	Decimals   int
	Address    string
	Underlying Token
}

// type FullTokenList struct {
// 	Chain map[string]map[string]Token `json:"chain"`
// }

// type TokenGroup string

// const (
// 	DexTokens  TokenGroup = "DEX_TOKENS"
// 	LPTokens   TokenGroup = "LP_TOKENS"
// 	IBCTokens  TokenGroup = "IBC_TOKENS"
// )

var DECIMALS = map[string]int{
	"Note":         18,
	"CANTO":        18,
	"USDC":         6,
	"USDT":         6,
	"ETH":          18,
	"ATOM":         6,
	"WETH":         18,
	"cNote":        18,
	"cCANTO":       18,
	"cUSDC":        6,
	"cUSDT":        6,
	"cETH":         18,
	"cATOM":        6,
	"CantoNoteLP":  18,
	"CCantoNoteLP": 18,
	"CantoAtomLP":  18,
	"cCantoAtomLP": 18,
	"NoteUSDCLP":   18,
	"cNoteUSDCLP":  18,
	"NoteUSDTLP":   18,
	"cNoteUSDTLP":  18,
	"CantoETHLP":   18,
	"cCantoETHLP":  18,
}

var TOKENS = map[string]map[string]Token{
	"CantoTestnet": {
		"CANTO": {
			Symbol:   "CANTO",
			Name:     "Canto",
			Decimals: DECIMALS["CANTO"],
			Address:  ADDRESSES.Testnet.CCantoNoteLP,
			IsERC20:  false,
			IsLP:     false,
		},
		"WCANTO": {
			Symbol:   "WCANTO",
			Name:     "WCanto",
			Decimals: DECIMALS["CANTO"],
			Address:  ADDRESSES.Testnet.WCANTO,
			IsERC20:  true,
			IsLP:     false,
		},
		"NOTE": {
			Symbol:   "NOTE",
			Name:     "Note",
			Decimals: DECIMALS["Note"],
			Address:  ADDRESSES.Testnet.Note,
			IsERC20:  true,
			IsLP:     false,
		},
		"ETH": {
			Symbol:   "ETH",
			Name:     "ETH",
			Decimals: DECIMALS["ETH"],
			Address:  ADDRESSES.Testnet.ETH,
			IsERC20:  true,
			IsLP:     false,
		},
		"ATOM": {
			Symbol:   "ATOM",
			Name:     "ATOM",
			Decimals: DECIMALS["ATOM"],
			Address:  ADDRESSES.Testnet.ATOM,
			IsERC20:  true,
			IsLP:     false,
		},
		"USDC": {
			Symbol:   "USDC",
			Name:     "USDC",
			Decimals: DECIMALS["USDC"],
			Address:  ADDRESSES.Testnet.USDC,
			IsERC20:  true,
			IsLP:     false,
		},
		"USDT": {
			Symbol:   "USDT",
			Name:     "USDT",
			Decimals: DECIMALS["USDT"],
			Address:  ADDRESSES.Testnet.USDT,
			IsERC20:  true,
			IsLP:     false,
		},
		"CantoNote": {
			Symbol:   "CantoNoteLP",
			Name:     "CantoNoteLP",
			Decimals: DECIMALS["CantoNoteLP"],
			Address:  ADDRESSES.Testnet.CantoNoteLP,
			IsERC20:  true,
			IsLP:     true,
		},
		"CantoAtom": {
			Symbol:   "CantoAtomLP",
			Name:     "CantoAtomLP",
			Decimals: DECIMALS["CantoAtomLP"],
			Address:  ADDRESSES.Testnet.CantoAtomLP,
			IsERC20:  true,
			IsLP:     true,
		},
		"NoteUSDC": {
			Symbol:   "NoteUSDCLP",
			Name:     "NoteUSDCLP",
			Decimals: DECIMALS["NoteUSDCLP"],
			Address:  ADDRESSES.Testnet.NoteUSDCLP,
			IsERC20:  true,
			IsLP:     true,
		},
		"NoteUSDT": {
			Symbol:   "NoteUSDTLP",
			Name:     "NoteUSDTLP",
			Decimals: DECIMALS["NoteUSDTLP"],
			Address:  ADDRESSES.Testnet.NoteUSDTLP,
			IsERC20:  true,
			IsLP:     true,
		},
		"CantoETH": {
			Symbol:   "CantoETHLP",
			Name:     "CantoETHLP",
			Decimals: DECIMALS["CantoETHLP"],
			Address:  ADDRESSES.Testnet.CantoETHLP,
			IsERC20:  true,
			IsLP:     true,
		},
	},
	"CantoMainnet": {
		"CANTO": {
			Symbol:   "CANTO",
			Name:     "Canto",
			Decimals: DECIMALS["CANTO"],
			Address:  ADDRESSES.CantoMainnet.WCANTO,
			IsERC20:  false,
			IsLP:     false,
		},
		"WCANTO": {
			Symbol:   "WCANTO",
			Name:     "WCanto",
			Decimals: DECIMALS["CANTO"],
			Address:  ADDRESSES.CantoMainnet.WCANTO,
			IsERC20:  true,
			IsLP:     false,
		},
		"NOTE": {
			Symbol:   "NOTE",
			Name:     "Note",
			Decimals: DECIMALS["Note"],
			Address:  ADDRESSES.CantoMainnet.Note,
			IsERC20:  true,
			IsLP:     false,
		},
		"ETH": {
			Symbol:   "ETH",
			Name:     "ETH",
			Decimals: DECIMALS["ETH"],
			Address:  ADDRESSES.CantoMainnet.ETH,
			IsERC20:  true,
			IsLP:     false,
		},
		"ATOM": {
			Symbol:   "ATOM",
			Name:     "ATOM",
			Decimals: DECIMALS["ATOM"],
			Address:  ADDRESSES.CantoMainnet.ATOM,
			IsERC20:  true,
			IsLP:     false,
		},
		"USDC": {
			Symbol:   "USDC",
			Name:     "USDC",
			Decimals: DECIMALS["USDC"],
			Address:  ADDRESSES.CantoMainnet.USDC,
			IsERC20:  true,
			IsLP:     false,
		},
		"USDT": {
			Symbol:   "USDT",
			Name:     "USDT",
			Decimals: DECIMALS["USDT"],
			Address:  ADDRESSES.CantoMainnet.USDT,
			IsERC20:  true,
			IsLP:     false,
		},
		"CantoNote": {
			Symbol:   "CantoNoteLP",
			Name:     "CantoNoteLP",
			Decimals: DECIMALS["CantoNoteLP"],
			Address:  ADDRESSES.CantoMainnet.CantoNoteLP,
			IsERC20:  true,
			IsLP:     true,
		},
		"CantoAtom": {
			Symbol:   "CantoAtomLP",
			Name:     "CantoAtomLP",
			Decimals: DECIMALS["CantoAtomLP"],
			Address:  ADDRESSES.CantoMainnet.CantoAtomLP,
			IsERC20:  true,
			IsLP:     true,
		},
		"NoteUSDC": {
			Symbol:   "NoteUSDCLP",
			Name:     "NoteUSDCLP",
			Decimals: DECIMALS["NoteUSDCLP"],
			Address:  ADDRESSES.CantoMainnet.NoteUSDCLP,
			IsERC20:  true,
			IsLP:     true,
		},
		"NoteUSDT": {
			Symbol:   "NoteUSDTLP",
			Name:     "NoteUSDTLP",
			Decimals: DECIMALS["NoteUSDTLP"],
			Address:  ADDRESSES.CantoMainnet.NoteUSDTLP,
			IsERC20:  true,
			IsLP:     true,
		},
		"CantoETH": {
			Symbol:   "CantoETHLP",
			Name:     "CantoETHLP",
			Decimals: DECIMALS["CantoETHLP"],
			Address:  ADDRESSES.CantoMainnet.CantoETHLP,
			IsERC20:  true,
			IsLP:     true,
		},
		//ibc tokens new
		"SOMM": {
			Symbol:   "SOMM",
			Name:     "Sommelier",
			Decimals: 6,
			Address:  "0xFA3C22C069B9556A4B2f7EcE1Ee3B467909f4864",
			IsERC20:  true,
			IsLP:     false,
		},
		"GRAV": {
			Symbol:   "GRAV",
			Name:     "Graviton",
			Decimals: 6,
			Address:  "0xc03345448969Dd8C00e9E4A85d2d9722d093aF8E",
			IsERC20:  true,
			IsLP:     false,
		},
		"AKASH": {
			Symbol:   "AKT",
			Name:     "Akash",
			Decimals: 6,
			Address:  "0x5aD523d94Efb56C400941eb6F34393b84c75ba39",
			IsERC20:  true,
			IsLP:     false,
		},
		"OSMOSIS": {
			Symbol:   "OSMO",
			Name:     "Osmosis",
			Decimals: 6,
			Address:  "0x0CE35b0D42608Ca54Eb7bcc8044f7087C18E7717",
			IsERC20:  true,
			IsLP:     false,
		},
		"CRESCENT": {
			Symbol:   "CRE",
			Name:     "Crescent",
			Decimals: 6,
			Address:  "0x5db67696C3c088DfBf588d3dd849f44266ff0ffa",
			IsERC20:  true,
			IsLP:     false,
		},
		"KAVA": {
			Symbol:   "KAVA",
			Name:     "Kava",
			Decimals: 6,
			Address:  "0xC5e00D3b04563950941f7137B5AfA3a534F0D6d6",
			IsERC20:  true,
			IsLP:     false,
		},
		"INJECTIVE": {
			Symbol:   "INJ",
			Name:     "Injective",
			Decimals: 18,
			Address:  "0x1D54EcB8583Ca25895c512A8308389fFD581F9c9",
			IsERC20:  true,
			IsLP:     false,
		},
		"COMDEX": {
			Symbol:   "CMDX",
			Name:     "Comdex",
			Decimals: 6,
			Address:  "0x3452e23F9c4cC62c70B7ADAd699B264AF3549C19",
			IsERC20:  true,
			IsLP:     false,
		},
		//new ibc tokens batch II
		"SENTINAL": {
			Symbol:   "DVPN",
			Name:     "Sentinal",
			Decimals: 6,
			Address:  "0x15C3Eb3B621d1Bff62CbA1c9536B7c1AE9149b57",
			IsERC20:  true,
			IsLP:     false,
		},
		"EVMOS": {
			Symbol:   "EVMOS",
			Name:     "Evmos",
			Decimals: 18,
			Address:  "0xF5b24c0093b65408ACE53df7ce86a02448d53b25",
			IsERC20:  true,
			IsLP:     false,
		},
		"PERSISTENCE": {
			Symbol:   "XPRT",
			Name:     "Persistence",
			Decimals: 6,
			Address:  "0xc8B4d3e67238e38B20d38908646fF6F4F48De5EC",
			IsERC20:  true,
			IsLP:     false,
		},
		"PStakedATOM": {
			Symbol:   "stkATOM",
			Name:     "PSTAKE staked ATOM",
			Decimals: 6,
			Address:  "0x50dE24B3f0B3136C50FA8A3B8ebc8BD80a269ce5",
			IsERC20:  true,
			IsLP:     false,
		},
		"STRIDE": {
			Symbol:   "STRD",
			Name:     "Stride",
			Decimals: 6,
			Address:  "0x13974cf36984216C90D1F4FC815C156092feA396",
			IsERC20:  true,
			IsLP:     false,
		},
		"STEVMOS": {
			Symbol:   "stEVMOS",
			Name:     "stEVMOS",
			Decimals: 18,
			Address:  "0x205CF44075E77A3543abC690437F3b2819bc450a",
			IsERC20:  true,
			IsLP:     false,
		},
		"STATOM": {
			Symbol:   "stATOM",
			Name:     "stATOM",
			Decimals: 6,
			Address:  "0x4A2a90D444DbB7163B5861b772f882BbA394Ca67",
			IsERC20:  true,
			IsLP:     false,
		},
		"STJUNO": {
			Symbol:   "stJUNO",
			Name:     "stJUNO",
			Decimals: 6,
			Address:  "0xe01C6D4987Fc8dCE22988DADa92d56dA701d0Fe0",
			IsERC20:  true,
			IsLP:     false,
		},
		"STOSMO": {
			Symbol:   "stOSMO",
			Name:     "stOSMO",
			Decimals: 6,
			Address:  "0x3515F25AB7637adcF1b69F4D384ed5936B83431F",
			IsERC20:  true,
			IsLP:     false,
		},
		"STSTARS": {
			Symbol:   "stSTARS",
			Name:     "stSTARS",
			Decimals: 6,
			Address:  "0x4AF57825b86Abf93D4F9D720bEF7c1C1b300A6F3",
			IsERC20:  true,
			IsLP:     false,
		},
		"QUICKSILVER": {
			Symbol:   "QCK",
			Name:     "Quicksilver",
			Decimals: 6,
			Address:  "0xF0965c8f0755CF080a61C91EDd6707F0532c8fE7",
			IsERC20:  true,
			IsLP:     false,
		},
		"QATOM": {
			Symbol:   "qATOM",
			Name:     "Quicksilver Liquid Staked ATOM",
			Decimals: 6,
			Address:  "0x9d6F2a9fDB32708e1AC07788cc29D6125ac73027",
			IsERC20:  true,
			IsLP:     false,
		},
		"QREGEN": {
			Symbol:   "qREGEN",
			Name:     "Quicksilver Liquid Staked Regen",
			Decimals: 6,
			Address:  "0xB5124FA2b2cF92B2D469b249433BA1c96BDF536D",
			IsERC20:  true,
			IsLP:     false,
		},
		"QSTARS": {
			Symbol:   "qSTARS",
			Name:     "Quicksilver Liquid Staked STARS",
			Decimals: 6,
			Address:  "0xD32eB974468ed767338533842D2D4Cc90B9BAb46",
			IsERC20:  true,
			IsLP:     false,
		},
		"WSTETH": {
			Symbol:   "wstETH",
			Name:     "wrapped staked eth",
			Decimals: 18,
			Address:  "0xc71aAf8e486e3F33841BB56Ca3FD2aC3fa8D29a8",
			IsERC20:  true,
			IsLP:     false,
		},
	},
	"ETHMainnet": {
		"USDT": {
			Symbol:   "USDT",
			Name:     "USDT",
			Decimals: DECIMALS["USDT"],
			Address:  ADDRESSES.ETHMainnet.USDT,
			IsERC20:  true,
			IsLP:     false,
		},
		"USDC": {
			Symbol:   "USDC",
			Name:     "USDC",
			Decimals: DECIMALS["USDC"],
			Address:  ADDRESSES.ETHMainnet.USDC,
			IsERC20:  true,
			IsLP:     false,
		},
		"WETH": {
			Symbol:   "WETH",
			Name:     "WETH",
			Decimals: DECIMALS["WETH"],
			Address:  ADDRESSES.ETHMainnet.WETH,
			IsERC20:  true,
			IsLP:     false,
		},
		"WSTETH": {
			Symbol:   "wstETH",
			Name:     "wrapped staked eth",
			Decimals: 18,
			Address:  "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
			IsERC20:  true,
			IsLP:     false,
		},
	},
	"GravityBridge": {
		"E2H": {
			Symbol:   "E2H",
			Name:     "E2H",
			Decimals: 18,
			Address:  ADDRESSES.GravityBridgeTest.E2H,
			IsERC20:  true,
			IsLP:     false,
		},
		"BYE": {
			Symbol:   "BYE",
			Name:     "BYE",
			Decimals: 18,
			Address:  ADDRESSES.GravityBridgeTest.BYE,
			IsERC20:  true,
			IsLP:     false,
		},
		"MAX": {
			Symbol:   "MAX",
			Name:     "MAX",
			Decimals: 18,
			Address:  ADDRESSES.GravityBridgeTest.MAX,
			IsERC20:  true,
			IsLP:     false,
		},
	},
}

var CTOKENS = map[string]map[string]CToken{
	"CantoTestnet": {
		"CCANTO": {
			Symbol:     "cCANTO",
			Name:       "cCanto",
			Decimals:   DECIMALS["cCANTO"],
			Address:    ADDRESSES.Testnet.CCanto,
			Underlying: TOKENS["CantoTestnet"]["CANTO"],
		},
		"CNOTE": {
			Symbol:     "cNOTE",
			Name:       "CNote",
			Decimals:   DECIMALS["cNote"],
			Address:    ADDRESSES.Testnet.CNote,
			Underlying: TOKENS["CantoTestnet"]["NOTE"],
		},
		"CETH": {
			Symbol:     "cETH",
			Name:       "CETH",
			Decimals:   DECIMALS["cETH"],
			Address:    ADDRESSES.Testnet.CETH,
			Underlying: TOKENS["CantoTestnet"]["ETH"],
		},
		"CATOM": {
			Symbol:     "cATOM",
			Name:       "CATOM",
			Decimals:   DECIMALS["cATOM"],
			Address:    ADDRESSES.Testnet.CATOM,
			Underlying: TOKENS["CantoTestnet"]["ATOM"],
		},
		"CUSDC": {
			Symbol:     "cUSDC",
			Name:       "CUSDC",
			Decimals:   DECIMALS["cUSDC"],
			Address:    ADDRESSES.Testnet.CUSDC,
			Underlying: TOKENS["CantoTestnet"]["USDC"],
		},
		"CUSDT": {
			Symbol:     "cUSDT",
			Name:       "CUSDT",
			Decimals:   DECIMALS["cUSDT"],
			Address:    ADDRESSES.Testnet.CUSDT,
			Underlying: TOKENS["CantoTestnet"]["USDT"],
		},
		"CCantoNote": {
			Symbol:     "CCantoNoteLP",
			Name:       "CCantoNoteLP",
			Decimals:   DECIMALS["CCantoNoteLP"],
			Address:    ADDRESSES.Testnet.CCantoNoteLP,
			Underlying: TOKENS["CantoTestnet"]["CantoNote"],
		},
		"CCantoAtom": {
			Symbol:     "cCantoAtomLP",
			Name:       "CCantoAtomLP",
			Decimals:   DECIMALS["cCantoAtomLP"],
			Address:    ADDRESSES.Testnet.CCantoAtomLP,
			Underlying: TOKENS["CantoTestnet"]["CantoAtom"],
		},
		"CNoteUSDC": {
			Symbol:     "cNoteUSDCLP",
			Name:       "CNoteUSDCLP",
			Decimals:   DECIMALS["cNoteUSDCLP"],
			Address:    ADDRESSES.Testnet.CNoteUSDCLP,
			Underlying: TOKENS["CantoTestnet"]["NoteUSDC"],
		},
		"CNoteUSDT": {
			Symbol:     "cNoteUSDTLP",
			Name:       "CNoteUSDTLP",
			Decimals:   DECIMALS["cNoteUSDTLP"],
			Address:    ADDRESSES.Testnet.CNoteUSDTLP,
			Underlying: TOKENS["CantoTestnet"]["NoteUSDT"],
		},
		"CCantoETH": {
			Symbol:     "cCantoETHLP",
			Name:       "CCantoETHLP",
			Decimals:   DECIMALS["cCantoETHLP"],
			Address:    ADDRESSES.Testnet.CCantoETHLP,
			Underlying: TOKENS["CantoTestnet"]["CantoETH"],
		},
	},
	"CantoMainnet": {
		"CCANTO": {
			Symbol:     "cCANTO",
			Name:       "CCanto",
			Decimals:   DECIMALS["cCANTO"],
			Address:    ADDRESSES.CantoMainnet.CCanto,
			Underlying: TOKENS["CantoMainnet"]["CANTO"],
		},
		"CNOTE": {
			Symbol:     "cNOTE",
			Name:       "CNote",
			Decimals:   DECIMALS["cNote"],
			Address:    ADDRESSES.CantoMainnet.CNote,
			Underlying: TOKENS["CantoMainnet"]["NOTE"],
		},
		"CETH": {
			Symbol:     "cETH",
			Name:       "CETH",
			Decimals:   DECIMALS["cETH"],
			Address:    ADDRESSES.CantoMainnet.CETH,
			Underlying: TOKENS["CantoMainnet"]["ETH"],
		},
		"CATOM": {
			Symbol:     "cATOM",
			Name:       "CATOM",
			Decimals:   DECIMALS["cATOM"],
			Address:    ADDRESSES.CantoMainnet.CATOM,
			Underlying: TOKENS["CantoMainnet"]["ATOM"],
		},
		"CUSDC": {
			Symbol:     "cUSDC",
			Name:       "CUSDC",
			Decimals:   DECIMALS["cUSDC"],
			Address:    ADDRESSES.CantoMainnet.CUSDC,
			Underlying: TOKENS["CantoMainnet"]["USDC"],
		},
		"CUSDT": {
			Symbol:     "cUSDT",
			Name:       "CUSDT",
			Decimals:   DECIMALS["cUSDT"],
			Address:    ADDRESSES.CantoMainnet.CUSDT,
			Underlying: TOKENS["CantoMainnet"]["USDT"],
		},
		"CCantoNote": {
			Symbol:     "CCantoNoteLP",
			Name:       "CCantoNoteLP",
			Decimals:   DECIMALS["CCantoNoteLP"],
			Address:    ADDRESSES.CantoMainnet.CCantoNoteLP,
			Underlying: TOKENS["CantoMainnet"]["CantoNote"],
		},
		"CCantoAtom": {
			Symbol:     "cCantoAtomLP",
			Name:       "CCantoAtomLP",
			Decimals:   DECIMALS["cCantoAtomLP"],
			Address:    ADDRESSES.CantoMainnet.CCantoAtomLP,
			Underlying: TOKENS["CantoMainnet"]["CantoAtom"],
		},
		"CNoteUSDC": {
			Symbol:     "cNoteUSDCLP",
			Name:       "CNoteUSDCLP",
			Decimals:   DECIMALS["cNoteUSDCLP"],
			Address:    ADDRESSES.CantoMainnet.CNoteUSDCLP,
			Underlying: TOKENS["CantoMainnet"]["NoteUSDC"],
		},
		"CNoteUSDT": {
			Symbol:     "cNoteUSDTLP",
			Name:       "CNoteUSDTLP",
			Decimals:   DECIMALS["cNoteUSDTLP"],
			Address:    ADDRESSES.CantoMainnet.CNoteUSDTLP,
			Underlying: TOKENS["CantoMainnet"]["NoteUSDT"],
		},
		"CCantoETH": {
			Symbol:     "cCantoETHLP",
			Name:       "CCantoETHLP",
			Decimals:   DECIMALS["cCantoETHLP"],
			Address:    ADDRESSES.CantoMainnet.CCantoETHLP,
			Underlying: TOKENS["CantoMainnet"]["CantoETH"],
		},
	},
}
