basePath: /v1
definitions:
  requestengine.Pairs:
    properties:
      blockNumber:
        type: string
      pairsStruct:
        items:
          $ref: '#/definitions/requestengine.ProcessedPair'
        type: array
    type: object
  requestengine.ProcessedPair:
    properties:
      address:
        type: string
      atob:
        type: boolean
      cdecimals:
        type: integer
      clpaddress:
        type: string
      decimals:
        type: integer
      lpPrice:
        type: string
      price1:
        type: string
      price2:
        type: string
      ratio:
        type: string
      reserve1:
        type: string
      reserve2:
        type: string
      stable:
        type: boolean
      symbol:
        type: string
      token0:
        $ref: '#/definitions/requestengine.Token'
      token1:
        $ref: '#/definitions/requestengine.Token'
      totalSupply:
        type: string
      tvl:
        type: string
    type: object
  requestengine.Token:
    properties:
      address:
        type: string
      chainId:
        type: integer
      decimals:
        type: integer
      logoURI:
        type: string
      name:
        type: string
      symbol:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Swagger UI for Cantor API
  title: Canto API
  version: "1.0"
paths:
  /dex/pairs:
    get:
      consumes:
      - application/json
      description: return json array of all pairs in Canto dex
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/requestengine.Pairs'
      summary: Query all pairs in Canto dex
  /lending/ctokens:
    get:
      consumes:
      - application/json
      description: return json array of all pairs in CLM
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Query all cTokens in CLM
swagger: "2.0"
